# Generated by Django 2.0.4 on 2020-06-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('dept', models.CharField(choices=[('CS', 'Computer Science And Engineering'), ('IT', 'Information Technology'), ('EEE', 'Electrical & Electronics Engineering'), ('EC', 'Electronics & Communication'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], max_length=70, verbose_name='Department')),
                ('dob', models.DateField(help_text='dd-mm-yyyy')),
                ('desig', models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Guest Faculty', 'Guest Faculty'), ('Assistant Professor', 'Assistant Professor')], default='Prof', max_length=20, verbose_name='Designation')),
                ('permaddr', models.TextField(max_length=50)),
                ('tempaddr', models.TextField(max_length=50)),
                ('category', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], default='Temporary', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=13)),
                ('status', models.CharField(max_length=10)),
                ('datejoin', models.DateField(blank=True, null=True)),
                ('dateresig', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultySubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('1', 'S1'), ('2', 'S2'), ('3', 'S3'), ('4', 'S4'), ('5', 'S5'), ('6', 'S6'), ('7', 'S7'), ('8', 'S8')], default='0', max_length=2, verbose_name='Semester')),
                ('branch', models.CharField(choices=[('CS', 'Computer Science And Engineering'), ('IT', 'Information Technology'), ('EEE', 'Electrical & Electronics Engineering'), ('EC', 'Electronics & Communication'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], default='A', max_length=50, verbose_name='Branch')),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1, verbose_name='Section')),
                ('year', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], verbose_name='Year Of Join')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Profile',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science And Engineering'), ('IT', 'Information Technology'), ('EEE', 'Electrical & Electronics Engineering'), ('EC', 'Electronics & Communication'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], max_length=70)),
                ('sem', models.CharField(choices=[('1', 'S1'), ('2', 'S2'), ('3', 'S3'), ('4', 'S4'), ('5', 'S5'), ('6', 'S6'), ('7', 'S7'), ('8', 'S8')], max_length=2)),
                ('stype', models.CharField(choices=[('T', 'Theory'), ('L', 'Practical'), ('P', 'Project')], max_length=15)),
                ('credit', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)])),
                ('dept', models.CharField(choices=[('CS', 'Computer Science And Engineering'), ('IT', 'Information Technology'), ('EEE', 'Electrical & Electronics Engineering'), ('EC', 'Electronics & Communication'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], max_length=60, verbose_name='Department')),
                ('theory_max_internal', models.PositiveIntegerField()),
                ('theory_max_external', models.PositiveIntegerField()),
                ('lab_max_internal', models.PositiveIntegerField()),
                ('lab_max_external', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='subject_profile',
            name='syllabussubid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='faculty.Syllabus'),
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='subcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='faculty.Subject_Profile', verbose_name='Subject Code'),
        ),
    ]
